import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PropsWithChildren } from "react";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const session = await auth();
  return (
    <html lang="ja">
      <SessionProvider session={session}>
        <body className={inter.className}>
          <div className="flex flex-col min-h-screen">
            <Header />
            <Toaster />
            <div className="flex-grow">{children}</div>
            <Footer />
          </div>
        </body>
      </SessionProvider>
    </html>
  );
}
